#!/bin/sh
uci set system.@system[0].hostname='ImmortalWrt-IPTV'
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].zonename='Asia/Shanghai'
uci commit system
/etc/init.d/iptv-perf enable
exit 0
