#!/bin/sh /etc/rc.common
USE_PROCD=1
START=94
STOP=10
BIN=/usr/bin/AdGuardHome-proxy
CONF=/etc/AdGuardHome-proxy.yaml
WORK=/var/lib/adguardhome-proxy
start_service() {
  [ -x "$BIN" ] || return 1
  mkdir -p "$WORK"
  mkdir -p /tmp/log
  procd_open_instance
  procd_set_param command "$BIN" -c "$CONF" -w "$WORK" --no-check-update --no-permcheck
  procd_set_param respawn 3600 5 5
  procd_set_param limits nofile="65535 65535"
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param file "$CONF"
  procd_close_instance
}
reload_service() { stop; start; }
